trigger:
  - main

pool:
  name: Default

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-25.jdk/Contents/Home'

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '**/site/jacoco/jacoco.xml'

